[package]
name = "mrf-manifest"
edition = "2024"
version = "0.1.0"

[dependencies]
fast-cjson = { version = "0.1.0", path = "../fast-cjson", optional = true }
leb128 = { version = "0.2.5", optional = true }
quick-error = { version = "2.0.1", optional = true }
schemars = { version = "1.0.4", features = ["semver1"] }
semver = { version = "1.0.26", features = ["serde"] }
serde = { version = "1.0.219", features = ["derive"] }
serde_json = { version = "1.0.142", optional = true }
wasm-encoder = { version = "0.236.0", optional = true }
wasmparser = { version = "0.236.0", optional = true }

[dev-dependencies]
insta = { version = "1.43.1", features = ["json"] }
wat = "1.236.0"

[features]
default = ["decode", "encode"]
decode = ["dep:leb128", "dep:quick-error", "dep:wasmparser"]
encode = ["dep:wasm-encoder", "serialise"]
serialise = ["dep:fast-cjson", "dep:serde_json"]

[lints]
workspace = true
