[package]
name = "tick-tock-mock"
edition = "2024"
version = "0.1.0"
license = "MIT OR Apache-2.0"

[[bench]]
name = "simple_now"
harness = false

[dependencies]

[dev-dependencies]
divan = "0.1.21"

[lints]
workspace = true
