[package]
name = "blowocking"
version = "0.1.0"
edition = "2024"

[dependencies]
quick-error = "2.0.1"
rayon = "1.10.0"
tokio = { version = "1.47.1", features = ["rt", "sync"] }
tracing = "0.1.41"

[lints]
workspace = true
