[package]
name = "tower-http-digest"
edition = "2024"
version = "0.1.0"

[dependencies]
base64 = "0.22.1"
bytes = "1.10.1"
either = "1.15.0"
http = "1.3.1"
http-body = "1.0.1"
memchr = "2.7.5"
pin-project-lite = "0.2.16"
sha2 = "0.10.9"
subtle = "2.6.1"
tower = "0.5.2"
tracing = "0.1.41"

[dev-dependencies]
futures-test = "0.3.31"
http-body-util = "0.1.3"
tower = { version = "0.5.2", features = ["util"] }

[lints]
workspace = true
