[package]
name = "mrf-tool"
description = "Tool for preparing and introspecting WASM MRFs"
edition = "2024"
version = "0.1.0"

[dependencies]
clap = { version = "4.5.43", features = ["derive"] }
color-eyre = "0.6.5"
colored_json = "5.0.0"
mrf-manifest = { version = "0.1.0", path = "../mrf-manifest" }
serde_json = "1.0.142"
wasmparser = "0.236.0"

[dev-dependencies]
wat = "1.236.0"
